### ISSUE TITLE
Question about aggregation method

### ISSUE THREAD

**Issue by aaossa** [fredhohman/summit-notebooks#6]
Hi,

I was reading the paper and taking some notes and I have a question about one of the formulas used to describe the "Aggregation Method 2". If I understand correctly, rows of Z^l matrix are scaled by dividing by the sum of the same row, which makes sense to me. But the formula displayed show a term where the denominator iterates over N, the number of images. That could also make some sense, but the objective of this aggregation is to determine the importance of the layer for a single image/row.

I left an example to make my question more clear, showing possible values to divide for. Do I need to divide each value in the matrix as shown in the top or the bottom of the figure? In that case, maybe the formula is wrong or am I reading it incorrectly?

![imagen](https://user-images.githubusercontent.com/10425834/97762547-a56bb900-1ae7-11eb-8444-e3ba028ba33f.png)

Thanks, 

PS: Loved this work 👌 Congrats 🎉

**Comment by fredhohman** [comment]
Hi @aaossa,

Thank you for the kind words and reaching out! I think you're right, we have a small bug in our equation notation... but all the text is accurate! **tl;dr:** use the green version in your graphic above that matches the paper text. I'll explain a bit more below. 

One row of this `Z^l` matrix represents the maximum activation per channel for a single image (your matrix on the left-hand-side above). 

We want a way to choose the top activated channels. Aggregation Method 1 from the paper simply picks the top `k`, say k=3 or k=5 channels. Aggregation Method 2 is adaptive in that it'll pick the top `k%` of channels based on converting the activations of a row (per image) to probability mass function (integral should sum to 1), in other words, trying to find the "knee" of the distribution (if you were to sort it). This is because one image may have 2 channels that are super important, but another image could have 4 channels that are super important. So finding this knee could be more accurate than the static `k` threshold from Method 1. 

To do this, we divide each row by its row sum so that each row (image) is now a probability distribution. So this is the green version of figure that matches the text. The equation fix should be summing over `j` not `i` in that denominator summation term. You'll find this matches the code too [in this notebook](https://github.com/fredhohman/summit-notebooks/blob/master/activation-matrices.ipynb): 

```
# METHOD 2: prob mass
working_acts_max = imgs_acts_max[i]/np.sum(imgs_acts_max[i])     <-- divide by row sum
```

Thank you for find this notation error! Hopefully this helps.

**Comment by aaossa** [comment]
That was a perfect explanation, really useful 👌 Also, now I manage to understand better your Method 2, which makes more sense to me now 🙌 Thanks!

**Comment by fredhohman** [comment]
You bet!
