### ISSUE TITLE
Input of "feature-vis-sprite-to-images.ipynb"

### ISSUE THREAD

**Issue by DicerZ** [fredhohman/summit-notebooks#7]
Hi @fredhohman, I am extending summit to my Resnet model which uses Pytoch. Could you provide some information about the input of "feature-vis-sprite-to-images.ipynb"?
```
# set path here

feature_vis_path = 'data/feature-vis/inceptionV1/'

filepaths = sorted(glob.glob(feature_vis_path + '*.jpg'))
```

**Comment by fredhohman** [comment]
Hi @DicerZ,

Very good! 

`feature-vis-sprite-to-images.ipynb` is simply an optional notebook that takes the sprite images from Distill's Feature Vis Appendix ([main url](https://distill.pub/2017/feature-visualization/appendix/), [example 1](https://distill.pub/2017/feature-visualization/appendix/googlenet/images/mixed3a-00000--mixed3a-00009.jpg), [example 2](https://distill.pub/2017/feature-visualization/appendix/googlenet/images/mixed3a-00010--mixed3a-00019.jpg)) and splits them up so that every feature-visualization/dataset-example/diversity-vis is its own image. 

You won't need to run this notebook again, as all the output I've already saved and organized here (the url structure should make sense): https://github.com/fredhohman/summit-data/tree/master/data/feature-vis

Feel free to share any results you get (either here, or you can email me directly)!

**Comment by fredhohman** [comment]
I'll close this issue for now, but feel free to reopen if you have more questions!

**Comment by DicerZ** [comment]
Thanks a lot for the quick reply! I've learned "summit-data" is based on Imagenet. Now I want to extend this work to my dataset. Could you give some advices about that?

**Comment by fredhohman** [comment]
I'll reply on the email you sent 👍
